default:
	./parse.rb baldy <raw/baldy_run_to_the_top_2017.txt >baldy_run_to_the_top_2017.json
	./parse.rb baldy <raw/baldy_run_to_the_top_2018.txt >baldy_run_to_the_top_2018.json
	./parse.rb athlinks <raw/mt_wilson_trail_race_2018.txt >mt_wilson_trail_race_2018.json 
	./parse.rb athlinks <raw/mt_wilson_trail_race_2019.txt >mt_wilson_trail_race_2019.json 
	./parse.rb athlinks <raw/broken_arrow_vk_2019.txt >broken_arrow_vk_2019.json
	./parse.rb ultrasignup <raw/flagstaff_sky_peaks_vk_2017.txt >flagstaff_sky_peaks_vk_2017.json
	./parse.rb athlinks <raw/pasadena_half_marathon_2020.txt >pasadena_half_marathon_2020.json


